version: '3'
services:
  brooksrybaproject:
    container_name: brooksrybaproject
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    networks:
    - application
  brooksrybaproject_api:
    container_name: brooksrybaproject_api
    build:
      context: ./
      dockerfile: Dockerfile-server
    volumes:
    - ./server/store.db:/app/server/store.db
    ports:
    - 3001:80
    networks:
    - application

networks:
  application:
    external: true
    name: brooksrybaproject_application
