# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Install Flask and its dependencies using pip
RUN pip install --trusted-host pypi.python.org flask gunicorn requests easypost sqlalchemy paypalrestsdk flask_cors python-dotenv

# Copy the current directory contents into the container at /app
COPY ./server /app

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the app using gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:80", "app:app"]