version: '3'
services:
  brooksrybaproject:
    container_name: brooksrybaproject
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    networks:
    - application
  brooksrybaproject_api:
    container_name: brooksrybaproject_api
    build:
      context: ./
      dockerfile: Dockerfile-server
    volumes:
    - db-data:/app/server/data
    ports:
    - 3001:80
    networks:
    - application

networks:
  application:
    external: true
    name: brooksrybaproject_application

volumes:
  db-data:
    driver: local
